services:
    frontend:
      build: ./frontend
      ports:
        - "3000:3000"
      environment:
        - NODE_ENV=development
      volumes:
        - ./frontend:/app
        - node_modules:/app/node_modules
      command: npm run dev
    db:
      image: postgres:13
      container_name: db
      restart: always
      environment:
        POSTGRES_USER: customlms
        POSTGRES_PASSWORD: customlms
        POSTGRES_DB: customlms
      ports:
        - "5432:5432"
      volumes:
        - db_data:/var/lib/postgresql/data

volumes:
    db_data: {}
    node_modules: