services:
    frontend:
      build: ./frontend
      ports:
        - "3000:3000"
      environment:
        - NODE_ENV=development
      volumes:
        - ./frontend:/app
      command: npm run dev

    backend:
      container_name: backend
      image: backend
      build:
        context: ./backend
        dockerfile: .dockerfile
      ports:
        - "4000:4000"
      environment:
        - DATABASE_URL="postgresql://customlms:customlms@db:5432/customlms?schema=public"
    db:
      image: postgres:15
      container_name: db
      restart: always
      environment:
        POSTGRES_USER: customlms
        POSTGRES_PASSWORD: customlms
        POSTGRES_DB: customlms
      ports:
        - "5432:5432"
      volumes:
        - postgres_data:/var/lib/postgresql/data

volumes:
    postgres_data: {}