services:
     frontend:
       build: ./frontend
       ports:
         - "3000:3000"
       environment:
         - NODE_ENV=development
       volumes:
         - ./frontend:/app
         - node_modules:/app/node_modules
       command: npm run dev

volumes:
    node_modules: